name: Docker Image CI

on:
  push:
    tags: [ "*" ]
  workflow_dispatch:
    inputs:
      version:
        description: Ren'Py Version number
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["base", "android", "ios"]

    steps:
    - uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push extra Docker images
      uses: docker/build-push-action@v5
      with:
        build-args: RENPY_VERSION=${{ github.event.inputs.version }}
        context: .
        file: ./Dockerfile.${{ matrix.version }}
        push: true
        tags: |
          ${{ github.event.inputs.version }}${{ matrix.version != 'base' && join(['-', matrix.version]) || '' }}
          ${{ matrix.version == 'base' && 'latest' || '' }}
