name: Docker Image CI

on:
  push:
    tags: [ "*" ]
  workflow_dispatch:
    inputs:
      version:
        description: Ren'Py Version number
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: ["base", "android", "ios"]

    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: dinaki/renpy
        tags: |
          type=semver,pattern={{version}},enable=${{ matrix.version == 'base' }}
          type=semver,pattern={{major}},enable=${{ matrix.version == 'base' }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ matrix.version == 'base' }}
          type=raw,value=latest,enable=${{ matrix.version == 'base' }}

          type=raw,value=${{ version }}-${{ matrix.version }},enable=${{ matrix.version != 'base' }}
          type=raw,value=${{ major }}-${{ matrix.version }},enable=${{ matrix.version != 'base' }}
          type=raw,value=${{ major }}.${{ minor }}-${{ matrix.version }},enable=${{ matrix.version != 'base' }}
          type=raw,value=${{ matrix.version }},enable=${{ matrix.version != 'base' }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push extra Docker images
      uses: docker/build-push-action@v5
      with:
        build-args: RENPY_VERSION=${{ github.event.inputs.version }}
        context: .
        file: ./Dockerfile.${{ matrix.version }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
